### ISSUE TITLE
as set of utility functions for lowdb,  extending notation

### ISSUE THREAD

**Issue by dkebler** [onury/notation#1]
You have a bunch of useful (and well documented) repos! super thx.    

If you had a little example code in the docs showing how to add them to lowdb at over 35K stars you'd get more exposure.  Maybe they'd even take a PR as an included set of utility functions, although a few duplicate stuff in underscore.   Still I might just drop lowdb and use notation since I'll probably do my own read/writes.  

Is there a supported way to extend notation like with lowdb?

```
db._

Database lodash instance. Use it to add your own utility functions or third-party mixins like underscore-contrib or underscore-db.

db._.mixin({
  second: function(array) {
    return array[1]
  }
})

const post1 = db.get('posts').first().value()
const post2 = db.get('posts').second().value()
```

**Comment by onury** [comment]
Thanks. I've never used lowdb - seems promising though.

Notation takes an object. Lowdb (db methods in general) work with arrays (i.e. result-sets). So this needs to be considered. 

I think you can mix notation in like below:
```js
db._.mixin({
  notateFirst: function (array) {
    var first = array[0].value();
    return (new Notation(first)).clone();
  }
})
```
Then you can do:
```js
const notation1 = db.get('posts').notateFirst();
notation1
    .merge({ 'my.newProp': 'here' })
    .remove('deep.down.prop')
    .value; // modified post value
```

Actually you wouldn't even need this. Just use the result object and init a Notation from that.
```js
const post1 = db.get('posts').first().value();
const notation1 = Notation.create(post1)
    .clone()
    .merge({ 'my.newProp': 'here' })
    .remove('deep.down.prop')
    .value;
```

Notation will/should not support mixins. It's not a (multi-goal) tool-belt. Rather, it's a goal-specific tool which needs to be improved with a clean roadmap. 

What is the feature you need, that Notation does not have already?
Thanks for the input.
