### ISSUE TITLE
Add support for sub-array / bracket notation

### ISSUE THREAD

**Issue by onury** [onury/notation#6]
e.g.  `prop[*].id` as Glob notation.  `*` indicates any index.
e.g. `prop[2].id` as notation. `2` indicates index 2.

Ball-park.. There are two files to be changed:

- [notation.glob.js](https://github.com/onury/notation/blob/master/src/core/notation.glob.js)
   - `compare`/`sort` should take `[*]` into account
   - `normalize` method should be updated
   - `union` method should be updated
- [notation.js](https://github.com/onury/notation/blob/master/src/core/notation.js)
   -  all applicable methods should support `[n]` (n is number, no globs)
   - `.filter` method should be updated. (this is the only method that accepts glob notation)

Should add new tests for each related method.
Existing and new tests should pass anyway.

**Comment by BenoitRanque** [comment]
Hi! Would you accept a PR for this?

**Comment by onury** [comment]
Hi @BenoitRanque. Sure I would. Thanks.

**Comment by BenoitRanque** [comment]
Another question while I work on this: do you have a requirement of support for older versions of javascript? Or can I use goodies like the Array prototype methods?

**Comment by onury** [comment]
I think, support for IE 10+ and newer is good enough.

**Comment by BenoitRanque** [comment]
Got it working, but somehow I'm failing the tests... Data looks good when I log it. I'll take another look later, in the meantime feel free to check out the dev branch of my fork. The filter function I rewrote entirely, it's still a prototype so I'm using things like `Object.keys()`, will move to the utils already provided when appropriate

https://github.com/BenoitRanque/notation/blob/dev/src/core/notation.js#L520

**Comment by BenoitRanque** [comment]
Will probably do a full rewrite of my full rewrite to better integrate with the methods already present

**Comment by onury** [comment]
Hi. You're making too many changes. Is it really to re-write the whole function(s) necessary?

**Comment by BenoitRanque** [comment]
Right now i'm just testing logic so I understand what is going on and can get it to pass tests. Once I get it, I'll try to rewrite as close as possible to original function.

**Comment by BenoitRanque** [comment]
Hi! Please take another look, it is done unless/until bugs are found. I have accidentally committed dev files, will clean that up later. All tests pass, including extra tests I added.

**Comment by onury** [comment]
Hi, thanks for working on this. 
Here is some findings at first look;

- [`Notation.isValid()`](https://github.com/onury/notation/compare/master...BenoitRanque:dev#diff-c0dc94e3218ddc836babf980ded9c88fR982) should only validate notation patterns, not globs. So `prop[*]` should not pass as valid. `prop.*` is valid only because `prop['*']` is possible in JS. It's not treated as a wildcard in `Notation` class. (Remember that only `Notation#filter()` should support globs in `notation.js`. For globs support, we have `NotationGlob` class.)

- There are very few tests for bracket notation. I added some tests: [notation.spec.js.zip](https://github.com/onury/notation/files/2042018/notation.spec.js.zip). Right now, most new tests fail unfortunately.

- Also, pls add `"semi": [2, "always"]` rule to eslintrc.json so that we always have semicolons at the end of statements.

**Comment by BenoitRanque** [comment]
Noted. Will do

**Comment by turakvlad** [comment]
Guys, any progress on it? Can I help in some way?

@onury, @BenoitRanque

**Comment by BenoitRanque** [comment]
Unfortunately I've been busy with work pressure and obligations, so I've not advanced on this since my last post

**Comment by marcinkumorek** [comment]
@onury  I've created a pull request. Please check if it's ok. https://github.com/onury/notation/pull/9
@BenoitRanque I've allowed myself to use some of your code from `notation.glob`, especially regex was a huge help.

**Comment by onury** [comment]
[Reviewed](https://github.com/onury/notation/pull/9#pullrequestreview-152259405). This is a great contribution.  
@marcinkumorek I'll merge this when you fix the final issues.

cheers !

**Comment by onury** [comment]
Sorry, been too busy. I've actually finished this. 
I'll release in a few days.

**Comment by Cyberuben** [comment]
I see there still hasn't been a new release.

Could you please get to releasing this, so that https://github.com/onury/accesscontrol/issues/23 can also be updated?

@onury

**Comment by jasonfutch** [comment]
+1

**Comment by dalvarezrDev** [comment]
I'm currently trying to implement this library on my project.
I've been testing the library so far and I like it. Only down side is that I ran across this issue of filtering arrays of nested objects (since I use MongoDB and that's how my Schema is made).

I see that this "feature request" has been opened for quite some time. So I'd love to know if this feature is actually going to be implemented (Since supposedly @onury already finished it).

I need to know if this repo is being maintained so that I could implement it on my project. You have done a great work with this repo.

**Comment by onury** [comment]
Finally implemented. :/
