### ISSUE TITLE
Normalize removing negated items with same start

### ISSUE THREAD

**Issue by RyanTheAllmighty** [onury/notation#7]
So I've been using `accesscontrol` to do filtering of objects based on roles and what attributes they have access to and I came across an issue that seems to track down to the `normalize` function of `notation`.

Given I have the following:

```js
// allow access to all except password and password_reset_code
const globs = [
    '*',
    '!password',
    '!password_reset_code'
];

// normalize them (called as part of filter but the issue remains in normalize)
const normalizedGlobs = normalize(globs);

// prints out ['*', '!password']
console.log(normalizedGlobs);
```

It seems `normalize` is stripping out all negated globs that start with another negated attirbute.

It seems to be caused by https://github.com/onury/notation/blob/master/src/core/notation.glob.js#L383 as it does a regex check, in my case, like below:

```js
/^password/.test('password_reset_code')
```

So any globs with the same beginning as a previous glob will be 'normalized' out.

Is this intended?

I've tried changing the ordering of the globs in the array and nothing seems to help short of changing the way I structure my data to ensure there is no repeated names.

**Comment by onury** [comment]
This is definitely a bug. Thanks for the report. Looking into it.

**Comment by onury** [comment]
This is auto-closed with the fix. Pls check it out and let me know if it works for you.

**Comment by RyanTheAllmighty** [comment]
Everything working as expected. Thanks for the super fast turn around time. Keep up the great work 👍
