### ISSUE TITLE
Mongo's `ObjectId` type is getting weird when passed to `.filter` function.

### ISSUE THREAD

**Issue by furqanaziz** [onury/notation#8]
MongoDB uses `ObjectId` type as a primary key for storing records and sub-records in the nested schema. When we pass the result of Mongo query, instead of returning same thing back (of at least return stringified version of it) `.filter` function is returning something like following:

```
It returns:
{{
  "_id": {
  "_bsontype": "ObjectID",
  "id":{
    "type": "Buffer",
    "data": [ 90, 216, 250, 230, 196, 47, 47, 0, 58, 78, 169, 254 ] }
  },
}}
```

**Comment by onury** [comment]
Notation does not support special, class-like objects. You should only use plain, data objects.
By "stringified" version, I guess you mean it's also parsed back to an object before passed to Notation. 

This result you get (with double curly braces) is not possible even in JS. Check out what it spits out when you do `console.log(JSON.stringify(result))`.

Also see [this](https://github.com/onury/accesscontrol/issues/20#issuecomment-334325012) and [this](https://github.com/onury/accesscontrol/issues/20#issuecomment-344470082) posts if relevant.
